### ISSUE TITLE
Please stop being disrespectful to real engineering (mechanical engineering is the ONLY engineering).

### ISSUE THREAD

**Issue by ghost** [Ombarus/pcg_planet_yt#5]
Hey @Ombarus, 
please stop making false claims about real Engineering. There is no such thing as "software" "engineering". That is most disrespectful lie ever. 

Please stop being disrespectful to real engineering (mechanical engineering is the ONLY engineering). Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. Engineering has nothing to do with sitting behind keyboard and writing code. 
Software dev is easy and has absolutely nothing to do with engineering. Engineering is a complex and deep subject, but software devs these days are being silly wannabe's when they start to talk about this great subject.

Mechanical Engineering is the ONLY engineering. Period.

Cheers

**Comment by Ombarus** [comment]
Engineering is a protected practice in Québec, Canada. It is managed by "[L'Ordre des Ingénieur du Québec](https://www.oiq.qc.ca/)" and only people registered with them are allowed to practice Engineering (https://engineerscanada.ca/accreditation/accredited-programs). I have a bachelor degree in "Génie Logiciel" from "L'école de Technologie Supérieur", a dedicated Engineering school in Montréal. 

That said, I cannot call myself a Software Engineer as I am no longer a member of the order (because I live in Japan right now). However I used to be a Junior Engineer when I graduated and so I believe I can talk about Software Engineering Principles.

Issues on github are to ask questions or report problems with the software in the repository.
